on:
  schedule:
    - cron: '0 20 * * 0'
  workflow_dispatch:

name: Auto Build for nightly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [guacd]
        # component: [guacd, guacenc]
        distro: [bullseye, bookworm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Set serial
        run: |
          serial=$(date "+%Y%m%d")
          echo "serial=${serial}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCRHUB_USERNAME }}
          password: ${{ secrets.GHCRHUB_TOKEN }}

      - name: Get Dockerfile
        run: |
          wget -O Dockerfile.guacd https://github.com/wojiushixiaobai/docker-library-loong64/raw/master/guacamole-server/nightly/slim-${{ matrix.distro }}/Dockerfile
          # wget -O Dockerfile.guacenc https://github.com/wojiushixiaobai/docker-library-loong64/raw/master/guacamole-server/nightly/slim-${{ matrix.distro }}/guacenc/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.${{matrix.component}}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            jumpserver/${{ matrix.component }}:${{ env.serial }}-${{ matrix.distro }}
            jumpserver/${{ matrix.component }}:nightly-${{ matrix.distro }}
            ghcr.io/jumpserver/${{ matrix.component }}:${{ env.serial }}-${{ matrix.distro }}
            ghcr.io/jumpserver/${{ matrix.component }}:nightly-${{ matrix.distro }}
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max