on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Version'
        required: true
        default: '1.5.5'
      freerdp_version:
        description: 'FreeRDP Version'
        required: true
        default: '2'

name: Checkout and Create Release Version

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ['guacd']
        # component: [guacd, guacenc]
        distro: ['bullseye', 'bookworm', 'trixie']
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.distro }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.distro }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCRHUB_USERNAME }}
          password: ${{ secrets.GHCRHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          provenance: false
          file: debian/${{ matrix.distro }}/Dockerfile
          platforms: ${{ matrix.distro == 'bullseye' && 'linux/amd64,linux/arm64' || 'linux/amd64,linux/arm64,linux/ppc64le,linux/s390x' }}
          push: true
          build-args: |
            VERSION=${{ github.event.inputs.version }}
            FREERDP_VERSION=${{ github.event.inputs.freerdp_version }}
          tags: |
            jumpserver/${{ matrix.component }}:${{ github.event.inputs.version }}-${{ matrix.distro }}
            ghcr.io/jumpserver/${{ matrix.component }}:${{ github.event.inputs.version }}-${{ matrix.distro }}
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache